---
- name: install additional packages
  pip:
    name: '{{ python_packages }}'
    state: present
    executable: '{{ executable_pip }}'
  environment:
    PATH: '/usr/local/bin:/usr/bin:{{ ansible_env.PATH }}'
